apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f585nah8q-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f585nah8q-java-quarkus-gitops